### ISSUE TITLE
Improve the Build Process

### ISSUE THREAD

**Issue by shockone** [shockone/black-screen#55]
* [x] Build with io.js. https://github.com/shockone/black-screen/issues/27
* [ ] Ensure `npm run package` isn't platform dependent. https://github.com/shockone/black-screen/issues/57
* [x] Read user's PATH. https://github.com/shockone/black-screen/issues/50
* [x] Do not include live reload into the build. https://github.com/shockone/black-screen/issues/32
* [x] Automatically create a binary on push. https://github.com/shockone/black-screen/issues/28
* [x] Try to concatenate all the files for shorter start time. https://github.com/shockone/black-screen/issues/193
* [x] Make it work on Linux. https://github.com/shockone/black-screen/issues/49
* [x] Replace the child_pty Library with pty.js. https://github.com/black-screen/black-screen/issues/83
* [x] Create homebrew cask for easy installation on Mac https://github.com/black-screen/black-screen/issues/77

**Comment by G07cha** [comment]
I have done some research about CI and I think that I can make continuous deployment with [Travis-CI](http://docs.travis-ci.com/user/deployment/releases/) or another CI but it's requires migrating on [git flow](http://nvie.com/posts/a-successful-git-branching-model/) model

**Comment by shockone** [comment]
@G07cha no problem, I'll happily use git flow. Thank you for investing your time again.

**Comment by joshtoo** [comment]
@G07cha @shockone - I can pick up the CI & CD workflow tasks.

**Comment by shockone** [comment]
@joshtoo cool, thank you.
